name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64 -t asifrdocker/cvrecommendation:tag .
        docker push asifrdocker/cvrecommendation:tag
      env:
        DOCKER_CLI_AGGREGATE: 1
